from __future__ import annotations

import os
import stat
from collections import OrderedDict
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import BinaryIO

from asset_autopsy.storage import ObjectIntegrityError, ObjectStore

from .schemas import ArtifactDescriptor


MAX_SESSION_ARTIFACTS = 256
MAX_SESSION_ARTIFACT_BYTES = 512 * 1024 * 1024


class ArtifactStoreError(RuntimeError):
    """Raised when a session artifact is absent or fails integrity checks."""


class SessionArtifactStore:
    """Bounded descriptor index over the shared content-addressed ObjectStore.

    The Studio keeps generated payloads outside Python heap memory and verifies
    their digest again on reads. Eviction is confined to this session's private
    object root; immutable revisions retain their Spec, but old generated bytes
    may need to be regenerated after the local artifact budget is exceeded.
    """

    def __init__(
        self,
        root: Path,
        *,
        maximum_artifacts: int = MAX_SESSION_ARTIFACTS,
        maximum_bytes: int = MAX_SESSION_ARTIFACT_BYTES,
    ) -> None:
        if maximum_artifacts < 1 or maximum_bytes < 1:
            raise ValueError("artifact budgets must be positive")
        self.objects = ObjectStore(root / "objects")
        self.maximum_artifacts = maximum_artifacts
        self.maximum_bytes = maximum_bytes
        self._descriptors: OrderedDict[str, ArtifactDescriptor] = OrderedDict()
        self._total_bytes = 0
        self._download_pins: dict[str, int] = {}
        self._display_pins: set[str] = set()
        self._pending_drops: set[str] = set()
        self._eviction_pending = False

    def put(self, descriptor: ArtifactDescriptor, content: bytes) -> None:
        if descriptor.byte_size > self.maximum_bytes:
            raise ArtifactStoreError("artifact exceeds the session byte budget")
        if len(content) != descriptor.byte_size:
            raise ArtifactStoreError("artifact byte size does not match its descriptor")
        try:
            reference = self.objects.put_bytes(
                content,
                expected_sha256=descriptor.sha256,
            )
        except (ObjectIntegrityError, ValueError) as error:
            raise ArtifactStoreError(
                "artifact could not be stored with its digest"
            ) from error
        if reference.bytes != descriptor.byte_size:
            raise ArtifactStoreError(
                "stored artifact size does not match its descriptor"
            )

        self._pending_drops.discard(descriptor.sha256)
        previous = self._descriptors.pop(descriptor.sha256, None)
        if previous is not None:
            self._total_bytes -= previous.byte_size
        self._descriptors[descriptor.sha256] = descriptor
        self._total_bytes += descriptor.byte_size
        self._evict_to_budget(protected={descriptor.sha256})

    def restore(self, descriptors: list[ArtifactDescriptor]) -> None:
        """Rebuild the bounded in-memory index from durable manifest metadata.

        Missing or corrupt historical objects are deliberately skipped. Their
        immutable Spec remains available and the compiler can regenerate them.
        Objects absent from durable manifests are removed so a process restart
        cannot hide their bytes from the session budget.
        """

        self._descriptors.clear()
        self._total_bytes = 0
        self._display_pins.clear()
        self._pending_drops.clear()
        self._eviction_pending = False
        for descriptor in descriptors:
            try:
                content = self.objects.read_bytes(descriptor.sha256)
            except (ObjectIntegrityError, ValueError):
                continue
            if len(content) != descriptor.byte_size:
                continue
            previous = self._descriptors.pop(descriptor.sha256, None)
            if previous is not None:
                self._total_bytes -= previous.byte_size
            self._descriptors[descriptor.sha256] = descriptor
            self._total_bytes += descriptor.byte_size
        while (
            len(self._descriptors) > self.maximum_artifacts
            or self._total_bytes > self.maximum_bytes
        ):
            _, descriptor = self._descriptors.popitem(last=False)
            self._total_bytes -= descriptor.byte_size
        self._remove_unindexed_objects()

    def read(self, digest: str) -> tuple[bytes, ArtifactDescriptor]:
        descriptor = self._descriptors.get(digest)
        if descriptor is None:
            raise ArtifactStoreError("artifact is not indexed in this session")
        try:
            content = self.objects.read_bytes(digest)
        except (ObjectIntegrityError, ValueError) as error:
            self._drop(digest)
            raise ArtifactStoreError(
                "artifact is missing or failed integrity checks"
            ) from error
        if len(content) != descriptor.byte_size:
            self._drop(digest)
            raise ArtifactStoreError("artifact size failed integrity checks")
        self._descriptors.move_to_end(digest)
        return content, descriptor

    def prepare_download(self, digest: str) -> "ArtifactDownload":
        """Verify and open one artifact without copying it into Python memory."""

        descriptor = self._descriptors.get(digest)
        if descriptor is None:
            raise ArtifactStoreError("artifact is not indexed in this session")
        self._download_pins[digest] = self._download_pins.get(digest, 0) + 1
        try:
            self.objects.verify(digest, expected_size=descriptor.byte_size)
            source = self.objects.path_for(digest).open("rb")
        except (ObjectIntegrityError, OSError, ValueError) as error:
            self.release_download(digest)
            self._drop(digest)
            raise ArtifactStoreError(
                "artifact is missing or failed integrity checks"
            ) from error
        self._descriptors.move_to_end(digest)
        return ArtifactDownload(source, descriptor, self)

    def release_download(self, digest: str) -> None:
        """Release one in-flight download and complete any deferred eviction."""

        pins = self._download_pins.get(digest, 0)
        if pins <= 1:
            self._download_pins.pop(digest, None)
            if digest in self._pending_drops:
                self._pending_drops.remove(digest)
                self._drop(digest)
            if self._eviction_pending:
                self._evict_to_budget()
            return
        self._download_pins[digest] = pins - 1

    def reserve_display_pins(self, digests: Sequence[str]) -> None:
        """Keep one displayed Build Pack boundedly readable across refreshes.

        Digests may be reserved before their bytes are written.  Build Pack
        generation uses that property so an earlier constituent cannot be
        evicted while later constituents are being stored under pressure.
        """

        self._display_pins.update(digests)

    @property
    def display_pins(self) -> frozenset[str]:
        return frozenset(self._display_pins)

    def replace_display_pins(self, digests: Sequence[str]) -> None:
        """Atomically select the one Build Pack that remains displayed."""

        self._display_pins = set(digests)
        if self._eviction_pending:
            self._evict_to_budget()

    def release_display_pins(self) -> None:
        """Release the displayed pack and finish any deferred eviction."""

        self._display_pins.clear()
        for digest in tuple(self._pending_drops):
            if not self._download_pins.get(digest):
                self._pending_drops.remove(digest)
                self._drop(digest)
        if self._eviction_pending:
            self._evict_to_budget()

    def __contains__(self, digest: object) -> bool:
        return isinstance(digest, str) and digest in self._descriptors

    @property
    def artifact_count(self) -> int:
        return len(self._descriptors)

    @property
    def total_bytes(self) -> int:
        return self._total_bytes

    def _evict_to_budget(self, *, protected: set[str] | None = None) -> None:
        protected = protected or set()
        while (
            len(self._descriptors) > self.maximum_artifacts
            or self._total_bytes > self.maximum_bytes
        ):
            digest = next(
                (
                    candidate
                    for candidate in self._descriptors
                    if (
                        candidate not in protected
                        and not self._download_pins.get(candidate)
                        and candidate not in self._display_pins
                    )
                ),
                None,
            )
            if digest is None:
                self._eviction_pending = True
                return
            self._drop(digest)
        self._eviction_pending = False

    def _remove_unindexed_objects(self) -> None:
        indexed = set(self._descriptors)
        directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW
        try:
            object_root_fd = os.open(self.objects.root, directory_flags)
        except FileNotFoundError:
            return
        except OSError as error:
            raise ArtifactStoreError(
                "artifact object root is invalid during restore"
            ) from error
        try:
            try:
                hash_root_fd = os.open("sha256", directory_flags, dir_fd=object_root_fd)
            except FileNotFoundError:
                return
            try:
                for prefix in os.listdir(hash_root_fd):
                    prefix_stat = os.stat(
                        prefix,
                        dir_fd=hash_root_fd,
                        follow_symlinks=False,
                    )
                    if prefix.startswith(".tmp-") and stat.S_ISREG(prefix_stat.st_mode):
                        os.unlink(prefix, dir_fd=hash_root_fd)
                        continue
                    if len(prefix) != 2 or any(
                        char not in "0123456789abcdef" for char in prefix
                    ):
                        continue
                    if not stat.S_ISDIR(prefix_stat.st_mode):
                        raise ArtifactStoreError(
                            "artifact object tree is invalid during restore"
                        )
                    prefix_fd = os.open(prefix, directory_flags, dir_fd=hash_root_fd)
                    try:
                        for digest in os.listdir(prefix_fd):
                            object_stat = os.stat(
                                digest,
                                dir_fd=prefix_fd,
                                follow_symlinks=False,
                            )
                            if (
                                len(digest) != 64
                                or not digest.startswith(prefix)
                                or any(
                                    char not in "0123456789abcdef" for char in digest
                                )
                            ):
                                continue
                            if not stat.S_ISREG(object_stat.st_mode):
                                raise ArtifactStoreError(
                                    "artifact object tree is invalid during restore"
                                )
                            if digest in indexed:
                                continue
                            os.unlink(digest, dir_fd=prefix_fd)
                    finally:
                        os.close(prefix_fd)
            finally:
                os.close(hash_root_fd)
        except OSError as error:
            raise ArtifactStoreError(
                "unindexed artifacts could not be removed during restore"
            ) from error
        finally:
            os.close(object_root_fd)

    def _drop(self, digest: str) -> None:
        if self._download_pins.get(digest) or digest in self._display_pins:
            self._pending_drops.add(digest)
            return
        descriptor = self._descriptors.pop(digest, None)
        if descriptor is None:
            return
        self._total_bytes -= descriptor.byte_size
        path = self.objects.path_for(digest)
        try:
            path.unlink(missing_ok=True)
        except OSError:
            # Drop the descriptor even if best-effort unlink fails so orphaned
            # bytes cannot be served; later generation cleanup may reclaim them.
            pass


@dataclass(slots=True)
class ArtifactDownload:
    source: BinaryIO
    descriptor: ArtifactDescriptor
    _store: SessionArtifactStore
    _closed: bool = False

    def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        try:
            self.source.close()
        finally:
            self._store.release_download(self.descriptor.sha256)


__all__ = [
    "ArtifactDownload",
    "ArtifactStoreError",
    "MAX_SESSION_ARTIFACT_BYTES",
    "MAX_SESSION_ARTIFACTS",
    "SessionArtifactStore",
]
