from __future__ import annotations

import os
import stat
from collections import OrderedDict
from pathlib import Path

from asset_autopsy.storage import ObjectIntegrityError, ObjectStore

from .schemas import ArtifactDescriptor


MAX_SESSION_ARTIFACTS = 256
MAX_SESSION_ARTIFACT_BYTES = 512 * 1024 * 1024


class ArtifactStoreError(RuntimeError):
    """Raised when a session artifact is absent or fails integrity checks."""


class SessionArtifactStore:
    """Bounded descriptor index over the shared content-addressed ObjectStore.

    The Studio keeps generated payloads outside Python heap memory and verifies
    their digest again on reads. Eviction is confined to this session's private
    object root; immutable revisions retain their Spec, but old generated bytes
    may need to be regenerated after the local artifact budget is exceeded.
    """

    def __init__(
        self,
        root: Path,
        *,
        maximum_artifacts: int = MAX_SESSION_ARTIFACTS,
        maximum_bytes: int = MAX_SESSION_ARTIFACT_BYTES,
    ) -> None:
        if maximum_artifacts < 1 or maximum_bytes < 1:
            raise ValueError("artifact budgets must be positive")
        self.objects = ObjectStore(root / "objects")
        self.maximum_artifacts = maximum_artifacts
        self.maximum_bytes = maximum_bytes
        self._descriptors: OrderedDict[str, ArtifactDescriptor] = OrderedDict()
        self._total_bytes = 0

    def put(self, descriptor: ArtifactDescriptor, content: bytes) -> None:
        if len(content) != descriptor.byte_size:
            raise ArtifactStoreError("artifact byte size does not match its descriptor")
        try:
            reference = self.objects.put_bytes(
                content,
                expected_sha256=descriptor.sha256,
            )
        except (ObjectIntegrityError, ValueError) as error:
            raise ArtifactStoreError(
                "artifact could not be stored with its digest"
            ) from error
        if reference.bytes != descriptor.byte_size:
            raise ArtifactStoreError(
                "stored artifact size does not match its descriptor"
            )

        previous = self._descriptors.pop(descriptor.sha256, None)
        if previous is not None:
            self._total_bytes -= previous.byte_size
        self._descriptors[descriptor.sha256] = descriptor
        self._total_bytes += descriptor.byte_size
        self._evict_to_budget()

    def restore(self, descriptors: list[ArtifactDescriptor]) -> None:
        """Rebuild the bounded in-memory index from durable manifest metadata.

        Missing or corrupt historical objects are deliberately skipped. Their
        immutable Spec remains available and the compiler can regenerate them.
        Objects absent from durable manifests are removed so a process restart
        cannot hide their bytes from the session budget.
        """

        self._descriptors.clear()
        self._total_bytes = 0
        for descriptor in descriptors:
            try:
                content = self.objects.read_bytes(descriptor.sha256)
            except (ObjectIntegrityError, ValueError):
                continue
            if len(content) != descriptor.byte_size:
                continue
            previous = self._descriptors.pop(descriptor.sha256, None)
            if previous is not None:
                self._total_bytes -= previous.byte_size
            self._descriptors[descriptor.sha256] = descriptor
            self._total_bytes += descriptor.byte_size
        while (
            len(self._descriptors) > self.maximum_artifacts
            or self._total_bytes > self.maximum_bytes
        ):
            _, descriptor = self._descriptors.popitem(last=False)
            self._total_bytes -= descriptor.byte_size
        self._remove_unindexed_objects()

    def read(self, digest: str) -> tuple[bytes, ArtifactDescriptor]:
        descriptor = self._descriptors.get(digest)
        if descriptor is None:
            raise ArtifactStoreError("artifact is not indexed in this session")
        try:
            content = self.objects.read_bytes(digest)
        except (ObjectIntegrityError, ValueError) as error:
            self._drop(digest)
            raise ArtifactStoreError(
                "artifact is missing or failed integrity checks"
            ) from error
        if len(content) != descriptor.byte_size:
            self._drop(digest)
            raise ArtifactStoreError("artifact size failed integrity checks")
        self._descriptors.move_to_end(digest)
        return content, descriptor

    def __contains__(self, digest: object) -> bool:
        return isinstance(digest, str) and digest in self._descriptors

    @property
    def artifact_count(self) -> int:
        return len(self._descriptors)

    @property
    def total_bytes(self) -> int:
        return self._total_bytes

    def _evict_to_budget(self) -> None:
        while (
            len(self._descriptors) > self.maximum_artifacts
            or self._total_bytes > self.maximum_bytes
        ):
            digest = next(iter(self._descriptors))
            self._drop(digest)

    def _remove_unindexed_objects(self) -> None:
        indexed = set(self._descriptors)
        directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW
        try:
            object_root_fd = os.open(self.objects.root, directory_flags)
        except FileNotFoundError:
            return
        except OSError as error:
            raise ArtifactStoreError(
                "artifact object root is invalid during restore"
            ) from error
        try:
            try:
                hash_root_fd = os.open("sha256", directory_flags, dir_fd=object_root_fd)
            except FileNotFoundError:
                return
            try:
                for prefix in os.listdir(hash_root_fd):
                    prefix_stat = os.stat(
                        prefix,
                        dir_fd=hash_root_fd,
                        follow_symlinks=False,
                    )
                    if prefix.startswith(".tmp-") and stat.S_ISREG(prefix_stat.st_mode):
                        os.unlink(prefix, dir_fd=hash_root_fd)
                        continue
                    if len(prefix) != 2 or any(
                        char not in "0123456789abcdef" for char in prefix
                    ):
                        continue
                    if not stat.S_ISDIR(prefix_stat.st_mode):
                        raise ArtifactStoreError(
                            "artifact object tree is invalid during restore"
                        )
                    prefix_fd = os.open(prefix, directory_flags, dir_fd=hash_root_fd)
                    try:
                        for digest in os.listdir(prefix_fd):
                            object_stat = os.stat(
                                digest,
                                dir_fd=prefix_fd,
                                follow_symlinks=False,
                            )
                            if (
                                len(digest) != 64
                                or not digest.startswith(prefix)
                                or any(
                                    char not in "0123456789abcdef" for char in digest
                                )
                            ):
                                continue
                            if not stat.S_ISREG(object_stat.st_mode):
                                raise ArtifactStoreError(
                                    "artifact object tree is invalid during restore"
                                )
                            if digest in indexed:
                                continue
                            os.unlink(digest, dir_fd=prefix_fd)
                    finally:
                        os.close(prefix_fd)
            finally:
                os.close(hash_root_fd)
        except OSError as error:
            raise ArtifactStoreError(
                "unindexed artifacts could not be removed during restore"
            ) from error
        finally:
            os.close(object_root_fd)

    def _drop(self, digest: str) -> None:
        descriptor = self._descriptors.pop(digest, None)
        if descriptor is None:
            return
        self._total_bytes -= descriptor.byte_size
        path = self.objects.path_for(digest)
        try:
            path.unlink(missing_ok=True)
        except OSError:
            # Drop the descriptor even if best-effort unlink fails so orphaned
            # bytes cannot be served; later generation cleanup may reclaim them.
            pass


__all__ = [
    "ArtifactStoreError",
    "MAX_SESSION_ARTIFACT_BYTES",
    "MAX_SESSION_ARTIFACTS",
    "SessionArtifactStore",
]
